---
- name: Install Docker on Alpine Linux
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apk:
        name:
          - docker
          - docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
